# Generated by Django 3.0 on 2020-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='images/')),
                ('book_desc', models.TextField()),
                ('book_subject', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], max_length=100)),
            ],
        ),
    ]
