# Generated by Django 3.0 on 2020-12-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_seller',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
            preserve_default=False,
        ),
    ]
