# Generated by Django 3.0 on 2020-12-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
