# Generated by Django 3.0 on 2020-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
