# Generated by Django 3.0 on 2021-01-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='net_amount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
